### PR TITLE
Add the feature retrieving the current location

### PR DESCRIPTION
**Pull request by keitaito**
- Retrieve the current location.
- Downloading ramen places data using the current location.
- Add LocationManager.
- Update Venue type from struct to class.
- Update Podfile settings.

### CODE REVIEW

**Comment by keitaito** [comment]
@lynneokada Please check this out when you have time. Thanks :octocat:

**Comment by keitaito** [comment]
By the way, I reverted your commit which was pushed to the master branch accidentally. After that, I changed the master branch to a protect branch. I think you are not able to push commits to the master branch.

**Comment by lynneokada** [comment]
I've pulled this to my local develop branch. I am also getting a Venue issue saying "Type 'Venue' does not conform to protocol 'GeneratorType'". I will keep looking into this, but do you also have any suggestions?

**Comment by lynneokada** [comment]
Oh! And thank you for all the work! :+1:

**Comment by keitaito** [comment]
@lynneokada I removed GeneratorType protocol from Venue type. Here is the deleted code:
https://github.com/keitaito/MenMa/commit/85758b183757f30aa4b65380cadefb65503ec048#diff-755768ae926369254a9c3b07de92b814L47
At line 47 in NetworkManager.swift.

**Comment by keitaito** [comment]
@lynneokada In your develop branch, does Venue type have GeneratorType protocol?

**Pull request merged**
